name: mmoMail
main: mmo.Mail.MMOMail
version: 0.1
author: FlayaN
depend: [mmoCore]
description: Simple mail system for players.
commands:
  mail:
    description: Invites, leaves, promotes...
    aliases: [m,mmomail]
    usage: /mail help