name: mmoMail
version: ${releaseVersion}.${buildNumber}
description: Provides a simply player mail system.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Mail.MMOMail
depend: [Spout, mmoCore]

commands:
    mail:
        description: Invites, leaves, promotes...
        aliases: [m, mmomail]
        usage: /mail help
